name: Deploy to Netlify (Windows)

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    runs-on: windows-latest  # Runs on Windows

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Use yarn or pnpm if needed

      - name: Build Project
        run: npm run build  # Adjust if your build command is different

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: |
          if ($env:GITHUB_REF_NAME -eq "main") {
            netlify deploy --prod --dir=.next/out
          } else {
            netlify deploy --alias=$env:GITHUB_REF_NAME --dir=.next/out
          }
        shell: pwsh
