name: Deploy to Netlify

on:
  push:
    branches:
      - main
      - development

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]  # Runs on all OS

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install  # Adjust for your package manager

      - name: Build Project
        run: npm run build  # Adjust if your build command is different

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: './dist'  # Change to your build directory
          production-branch: main
          deploy-message: "Deployed via GitHub Actions from ${{ runner.os }}"
          enable-pull-request-comment: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
          alias: ${{ github.ref_name }}  # Creates a preview deployment for development
